### ISSUE TITLE
Epsódio #1

### ISSUE THREAD

**Issue by avelino** [erichideki/mesadebar#1]
Coloque nos comentários sugestões para pauta.

**Comment by alexaleluia12** [comment]
Event-driven programming in Python está restrita somente a web com Twisted/Tornado ?
Existe algo como EventEmitter de node que permite criar seus proprios eventos e callbacks ?

**Comment by maugravena** [comment]
Sugestão de projetos python para iniciantes, para efeito de estudos

**Comment by di3goleite** [comment]
Raspagem de dados com Scrapy.

**Comment by camilotx** [comment]
Se não for somente assuntos sobre python, mas com ele incluso, recomendo o assunto polyglot programing. O assunto é pouco explorado.

**Comment by Gpzim98** [comment]
Estruturação de ambientes de desenvolvimento para sistemas legados!

Ex.: Workflow ideal usando Git. (Branches, Pull request para code review, trabalho em equipe, rastreabilidade de funcionalidades, Code Climates em linguagens antigas)

**Comment by alansammarone** [comment]
Multithreading, multiprocessing e GIL

**Comment by erichideki** [comment]
Python para processamento de imagens com Pillow

**Comment by vinimatos** [comment]
Arquitetura D-D-D(driven domain design python) em Django =)

**Comment by daniellbastos** [comment]
Segundos passos com Django, pra onde seguir depois de aprender o hello world

**Comment by erichideki** [comment]
O que é uma comunidade?

**Comment by MarcoWorms** [comment]
Um conjunto de seres que interagem entre si tentando sempre alcançarem um determinado objetivo por meio de ajuda mútua?

**Comment by lipemorais** [comment]
Open Talks

https://www.eventick.com.br/open-talks
https://www.facebook.com/events/1572496593001458/
