### ISSUE TITLE
Episódio #4

### ISSUE THREAD

**Issue by avelino** [erichideki/mesadebar#10]

**Comment by lerrua** [comment]
Queria sugerir tema, algo do tipo "o mundo fora do Django". Vejo direto pessoal novo na comunidade ou mesmo de outras linguagens só enchergando o Django como opção para desenvolvimento web. Acho que seria interessante bater um papo e principalmente, mostrar cases reais aqui no Brasil da galera usando outros frameworks.

**Comment by erichideki** [comment]
Boa ideia. Mas podemos falar de outros frameworks que conhecemos de outras linguagens também.

**Comment by avelino** [comment]
@erichideki podemos fazer um semana de Python, outra ruby e ...

**Comment by lipemorais** [comment]
Por favor, me corrijam se estiver errado.

@avelino, acho um pouco difícil fechar em uma linguagem ou tecnologia, quando a gente falar de um legal vamos lembrar, e fazer com que os outros lembrem, de outros legais em outras linguagens.

Me parece que a ideia é falar de frameworks legais, seus pontos positivos e negativos, quando usar cada um deles, quem usou e deu certo dizer os porques, quem usou e deu errado e seus porques.
Entendi certo @lerrua?

**Comment by lerrua** [comment]
Exatamente isso @lipemorais.
Importante pessoal da comunidade citar suas experiências com outros frameworks, não importa a linguagem. Trabalhei com Rails por dois anos (e ainda estou pegando um projeto atualmente), com certeza vou tentar citar ele, comparando com outros frameworks que já trabalhei. 
Um dos objetivos é mostrar pro pessoal que no mundo Python não é apenas Django. Pelo menos essa é a ideia que joguei na issue, se a galera curtir então vamos seguindo nela.

**Comment by lipemorais** [comment]
Eu gostei da ideia! o/
Quando eu comecei vi um pouco de Rails e hoje o que mais vejo é Django
queria ver um overview sobre outros frameworks, seria legal.

**Comment by dbatistasa** [comment]
Só para complicar mais. Alguém já usou alguma solução de BPM em Python?

Em 29 de março de 2015 22:23, Felipe de Morais <notifications@github.com>
escreveu:

> Eu gostei da ideia! o/
> Quando eu comecei vi um pouco de Rails e hoje o que mais vejo é Django
> queria ver um overview sobre outros frameworks, seria legal.
>
> On Sun, Mar 29, 2015, 21:51 Igor P. Leroy <notifications@github.com>
> wrote:
>
> > Exatamente isso @lipemorais <https://github.com/lipemorais>.
> > Importante pessoal da comunidade citar suas experiências com outros
> > frameworks, não importa a linguagem. Trabalhei com Rails por dois anos (e
> > ainda estou pegando um projeto atualmente), com certeza vou tentar citar
> > ele, comparando com outros frameworks que já trabalhei.
> > Um dos objetivos é mostrar pro pessoal que no mundo Python não é apenas
> > Django. Pelo menos essa é a ideia que joguei na issue, se a galera curtir
> > então vamos seguindo nela.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/erichideki/mesadebar/issues/10#issuecomment-87504664
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erichideki/mesadebar/issues/10#issuecomment-87507579>.
>



-- 
Daniel Sá

**Comment by linuxsoares** [comment]
Java não entra ai não? 
Hoje temos PlayFramework que funciona da mesma forma que um Django ou mesmo Rails... 
Sugestão apenas rs

**Comment by avelino** [comment]
@linuxsoares entra sim, só precisamos de pessoas para falar, seja bem vindo :smile:

**Comment by kalkehcoisa** [comment]
É um tema interessante. Estou trabalhando com Pyramid faz algum tempo já. Se quiserem, posso preparar alguma coisa.
Tem alguma previsão de quando vai ser o próximo?

**Comment by avelino** [comment]
@kalkehcoisa o proximo é hoje :D

**Comment by kalkehcoisa** [comment]
Puts! Queria ter visto sua msg antes. ><
