### ISSUE TITLE
Episódio para tirar dúvidas da PythonBrasil

### ISSUE THREAD

**Issue by renzon** [erichideki/mesadebar#15]
Respoder perguntas frequentes:

* O que são Tutoriais?
* O que são Palestras?
* O que é Sprint?
* Palestrante tem desconto?
* Estudante tem desconto?
* Mulher tem desconto?
* Por que ingresso para empresa e setor público é mais caro?

...

https://github.com/erichideki/mesadebar/blob/master/episodio7.md

**Comment by Gpzim98** [comment]
O que são Lightalks? Qualquer um pode fazer?

**Comment by raphapassini** [comment]
A história do sequestro merece ser contada @renzon :)

**Comment by renzon** [comment]
@raphapassini já trolhando na thread....kkkk

**Comment by erichideki** [comment]
Hahahaha, não sabia que estava documentada.

**Comment by avelino** [comment]
- Como organizar uma PythonBrasil[]?
- Como ser o próximo big kahuna?
- Dicas como lidar com burocracia na organização de uma PythonBrasil?
- Qual é o maior desafio de organizar uma PythonBrasil?

**Comment by lgarciasbr** [comment]
Eu preciso apresentar o tema das palestras na empresa que trabalho para mostrar a relevância do evento para o meu time. Já existe uma lista das palestras / temas que serão abordados?

**Comment by renzon** [comment]
É possível participar dos tutoriais e não das palestras, e vice-versa?

**Comment by lidymonteirowm** [comment]
Como funciona a área open space? (horário de funcionamento, como participar e duração de cada atividade)

**Comment by raphapassini** [comment]
A Python Brasil é aberta para pessoas iniciantes ou que venham de outras linguagens como Ruby por exemplo?

**Comment by taniaa** [comment]
Dúvida: dá pra já responder as dúvidas aqui ou tem que esperar o hangout? :D

**Comment by GuidoBR** [comment]
- Dicas de hotéis próximos
- Como chegar ao local do evento pra quem não entende nada de SP :)

**Comment by renzon** [comment]
Por que patrocínios com brindes e sorteios não são aceitos?

**Comment by renzon** [comment]
@taniaa Não vejo problema em responder por aqui. Mas de toda forma, vou repetir no vídeo para poder indicar sempre que as dúvidas surgirem ;)

**Comment by avelino** [comment]
- [Código de Conduta APyB](https://github.com/pythonbrasil/codigo-de-conduta), um overview sobre o que é e para que server e onde se aplica dentro da PythonBrasil[11]

**Comment by erichideki** [comment]
@GuidoBR Fiz um negócio aqui, nada oficial e ainda irá ser melhorado, mas já dá umas ideias de como se localizar por SJC - https://mapa-pybr11.herokuapp.com/

**Comment by GuidoBR** [comment]
Muito obrigado @erichideki !

Mais uma semi-relacionada:

- O que é big kahuna?
