### ISSUE TITLE
Qual o processo de escrever/traduzir um livro?

### ISSUE THREAD

**Issue by avelino** [erichideki/mesadebar#2]
Como o @erichideki trabalha hoje na novatec, nada como Rubens ser um convidado para falar desse processos...

**Comment by erichideki** [comment]
Consegui uma parceria com a Carolina para poder falar a respeito :), agora é fechar a data.

**Comment by luzfcb** [comment]
@avelino @erichideki na espera. Esse é um assunto que tenho muita vontade de conhecer mais.
