### ISSUE TITLE
Episódio #3

### ISSUE THREAD

**Issue by erichideki** [erichideki/mesadebar#5]

**Comment by erichideki** [comment]
Trabalho Home office. Como funciona? Quais são as formas? CLT? MEI? PJ? Quem contrata? Existe vagas boas remotas?

**Comment by avelino** [comment]
@erichideki otimo assunto, depois de 5 anos trabalhando home office tenho um pouco de bagagem para falar sobre esse assunto!

**Comment by jonasporto** [comment]
por acaso, encontrei esse link vagando em algum grupo do fb.
https://github.com/DyegoCosta/trabalhando-remoto

**Comment by dbatistasa** [comment]
Gostaria muito de ouvir a experiência de todos.

**Comment by lipemorais** [comment]
Gostaria de saber sobre também. Trabalhei alguns dias de casa está semana e
ganhei 4h do meu dia que eu perdia no transporte, sem falar que me sinto
muito mais descansado ao fim do dia.

**Comment by inacioloy** [comment]
Também tenho interesse no assunto, gostaria de saber da experiência de vocês.

**Comment by klebercode** [comment]
Excelente assunto, acredito que irá ajudar bastante a galera.

**Comment by luzfcb** [comment]
@huogerac alguma opinião sobre o assunto? XD

**Comment by ivancrneto** [comment]
meus 2 centavos:
- ter duas internets, um 4G e um no-break.
- ter uma sala separada, que possa ser trancada.
- ter um bom fone que não dê eco.
- criar "rituais" de transição pra mostrar ao seu cérebro se você está "em casa" ou "no trabalho" no momento.

;)

**Comment by lerrua** [comment]
+1 @ivancrneto 

@erichideki se possível nessa mesa de bar gostaria de participar, desde 2011 brinco de home office, tive experiencies ótimas e também péssimas. Se meu 3G na casa nova ajudar, eu tô dentro.

**Comment by mayckxavier** [comment]
Meus 2 centavos:
* Ter um computador de backup
* Backup de arquivos. Eu tenho 1 hd para cada computador (tenho 2 computadores) e um backup online com o Crashplan. Backup nunca é demais.
* Telefone perto de você. Agora mesmo tive que ligar pra um cliente e tive que usar o celular por que o fixo está na sala. Perdi alguns centavos nisso.
* Mobília decente. Decente = confortável pra você

**Comment by dbatistasa** [comment]
Mayck, caso você utilize a GVT para linha fixa, existe um app chamado GVT
Freedom, que transforma seu celular em uma extensão móvel.

https://play.google.com/store/apps/details?id=com.gvt.android.freedom

Em 24 de março de 2015 15:43, Mayck Xavier <notifications@github.com>
escreveu:

> Meus 2 centavos:
>
>    - Ter um computador de backup
>    - Backup de arquivos. Eu tenho 1 hd para cada computador (tenho 2
>    computadores) e um backup online com o Crashplan. Backup nunca é demais.
>    - Telefone perto de você. Agora mesmo tive que ligar pra um cliente e
>    tive que usar o celular por que o fixo está na sala. Perdi alguns centavos
>    nisso.
>    - Mobília decente. Decente = confortável pra você
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erichideki/mesadebar/issues/5#issuecomment-85638053>.
>



-- 
Daniel Sá

**Comment by mayckxavier** [comment]
@dbatistasa, não. Uso NET e nem sei se eles tem algo parecido.
Acho que não tem GVT aqui na minha área, mas mesmo assim, muito obrigado!

**Comment by guilhermebr** [comment]
Boa, trabalho home office tem 2 anos, posso contribuir também =]

**Comment by erichideki** [comment]
Só pra esquentar:

https://osantana.me/programador-freelancer/

https://osantana.me/trabalho-remoto/

**Comment by felipepavao** [comment]
Galera, sou fã desse tema e gostaria de participar. Legal evoluirmos esse tipo de discussao.

**Comment by gigante** [comment]
Onde encontrar empresas que aceitam trabalho remoto? Tópico interessante

**Comment by gabrielcesar** [comment]
Muito bom mesmo o tema @erichideki, parabéns. E acredito que do interesse de todos. As empresas e desenvolvedores economizam tempo, dinheiro entre outras coisas. É uma forte tendência que será mais e mais adotada daqui para frente.

Minha sugestão é para trocarmos experiências sobre quais ferramentas estamos usando para isso e, o mais importante, como aprimorá-las. Slack, Skype, Whatsapp. ;)

**Comment by berlotto** [comment]
Eu trabalho homeoffice a 2 meses ! heheheh Vamos nessa...

**Comment by humrochagf** [comment]
Hehe, eu comecei a trabalhar de home office agora, vai fazer um mês \o/

**Comment by klebercode** [comment]
Será hoje?

**Comment by avelino** [comment]
Sim, segue informacões...
https://github.com/erichideki/mesadebar/blob/master/episodio3.md
Chat: http://webchat.freenode.net/?channels=mesadebar

**Comment by luzfcb** [comment]
Vai começar:

https://www.youtube.com/watch?v=GPhH6t52veU

IRC online:

http://webchat.freenode.net/?channels=mesadebar

ou entre no canal #mesadebar no freenode


2015-03-25 20:11 GMT-03:00 Kleber Soares <notifications@github.com>:

> Será hoje?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erichideki/mesadebar/issues/5#issuecomment-86249120>.
>



-- 
Fábio C. Barrionuevo da Luz
Acadêmico de Sistemas de Informação na Faculdade Católica do Tocantins -
FACTO
Palmas - Tocantins - Brasil - América do Sul

http://pythonclub.com.br/

Blog colaborativo sobre Python e tecnologias Relacionadas, mantido
totalmente no https://github.com/pythonclub/pythonclub.github.io .

Todos são livres para publicar. É só fazer fork, escrever sua postagem e
mandar o pull-request. Leia mais sobre como publicar em README.md e
contributing.md.
Regra básica de postagem:
"Você" acha interessante? É útil para "você"? Pode ser utilizado com Python
ou é útil para quem usa Python? Está esperando o que? Publica logo, que
estou louco para ler...

**Comment by huogerac** [comment]
eae @luzfcb ...

Olá pessoal, ainda sou um pouco recente no trabalho remoto, um pouco mais de 1 ano apenas.

Vou contar um pouco do meu ponto de vista e espero que isto possa ajudar alguns que sonham em trabalhar de casa.
A empresa que trabalho NÃO tinha home office e hoje ela é 100% trabalho remoto (isto mesmo, não temos escritório).
A questão não precisa ser apenas achar vagas para trabalhar remotamente. Você pode transformar o local onde trabalha. Da mesma forma que podemos melhorar nosso ambiente de trabalho em diversos outros aspectos, podemos iniciar a cultura do home office.

AVISOS:
- Nem todo mundo consegue/sabe trabalhar remotamente
- Alguns gerentes vão usar aquele cara que abusa da 'mobilidade' para rotular que esta prática é razão para o atraso no projeto
- Cuidado com o “the grass is always greener on the other side”

Enfim, a melhor forma é começar a conquistar a confiança e mostrar as diversas vantagens de fazer 1 ou 2 dias de home office no seu trabalho atual. 
É impressionante como problemas aparecem e achamos soluções e vamos nos adaptando. Desde de ferramentas até práticas de desenvolvimento de softwares.

p.s.:
- Não confunda trabalho remoto com flexibilidade. Você pode trabalhar de casa e não ter tempo para nada, bem como você pode 'bater ponto' trabalhando apenas 2 ou 3 dias e ter metade da semana livre para dedicar no que gosta. Ai entra o papo de autonomia também... 
- Não sei a explicação, mas time organizado remotamente tende a diminuir aquelas discuções perda de tempo que muitas vezes viram longas threads em empreas, não chegam em lugar nenhum e podem até gerar inimizades, ex: Usar 2 ou 4 espaços na indentação, Usar Django 1.6.1 ou 1.6.11?

[]'s
